### ISSUE TITLE
Typo in Class TouchscreenDevice

### ISSUE THREAD

**Issue by snyh** [fontanon/udev-discover#13]
https://github.com/fontanon/udev-discover/blob/3b724a98cd3bf82f1b1197d072c1e468a007c52f/udevdiscover/device/input/touchscreen.py#L24

The typo will cause import error when there has a touchscreen device.  
https://github.com/fontanon/udev-discover/blob/master/udevdiscover/device/input/__init__.py#L43

**Comment by fontanon** [comment]
Merged! Thanks.
